name: jaafari_guide
description: "Jaafari Guide - A professional study and tests guide application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.0
  syncfusion_flutter_pdfviewer: ^33.2.4
  path_provider: ^2.1.2
  http: ^1.2.0
  file_picker: ^11.0.2
  cached_network_image: ^3.3.1
  
  # المكتبات الثلاثة التي كانت ناقصة:
  flutter_cache_manager: ^3.3.2
  intl: ^0.20.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true