// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVP9grA3jde13rw9DDGEoBz30l92p6mW8',
    appId: '1:838641477113:web:09fcfb3f3e26042b2e8928',
    messagingSenderId: '838641477113',
    projectId: 'jaafari-guide-56f12',
    authDomain: 'jaafari-guide-56f12.firebaseapp.com',
    storageBucket: 'jaafari-guide-56f12.firebasestorage.app',
    measurementId: 'G-GKVF6PHSWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLeuLaSG1jhiGhx3wz3vbLQDHBr1VIDU',
    appId: '1:838641477113:android:678a55545302c0812e8928',
    messagingSenderId: '838641477113',
    projectId: 'jaafari-guide-56f12',
    storageBucket: 'jaafari-guide-56f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtpqMRYUUAApyCzX6imyOd6JuKNdMecQ',
    appId: '1:838641477113:ios:7742583f9a3f1e5e2e8928',
    messagingSenderId: '838641477113',
    projectId: 'jaafari-guide-56f12',
    storageBucket: 'jaafari-guide-56f12.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtpqMRYUUAApyCzX6imyOd6JuKNdMecQ',
    appId: '1:838641477113:ios:7742583f9a3f1e5e2e8928',
    messagingSenderId: '838641477113',
    projectId: 'jaafari-guide-56f12',
    storageBucket: 'jaafari-guide-56f12.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVP9grA3jde13rw9DDGEoBz30l92p6mW8',
    appId: '1:838641477113:web:c954b3b38dc5a46f2e8928',
    messagingSenderId: '838641477113',
    projectId: 'jaafari-guide-56f12',
    authDomain: 'jaafari-guide-56f12.firebaseapp.com',
    storageBucket: 'jaafari-guide-56f12.firebasestorage.app',
    measurementId: 'G-YHJLMVWRS6',
  );
}
